format_version: 3
environments:
  testing:
    environment_variables:
      DEPLOYMENT: testing
    secure_variables:
      ENV_PASSWORD: "s&Du#@$xsSa"
    pipelines:
      - example-deploy-testing
      - build-testing
pipelines:
  ovoex:
    group: services
    label_template: "${mygit[:8]}"
    lock_behavior: none
    materials:
      master: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        git: git@github.com:NAJ10/greeting-service.git
        branch: master
    stages: # list of stages in order
      - build: # name of stage
          clean_workspace: true
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: sbt
                   arguments:
                    - test
